common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV["HOST_NAME"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>

development:
  <<: *common
  database: <%= ENV["MOVIE_REVIEWS_DEV"] %>

test:
  <<: *common
  database: <%= ENV["MOVIE_REVIEWS_TEST"] %>

staging:
  <<: *common
  database: <%= ENV["MOVIE_REVIEWS_STG"] %>

production:
  <<: *common
  database: <%= ENV["MOVIE_REVIEWS_PROD"] %>
